FROM node:13.7.0-alpine

EXPOSE 9000

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

# Set default command
CMD [ "npm", "start" ]
